name: "leonardorifeli"
description: ""
meta_description: "Leonardo Rifeli - Head of Engineering & Partner at reviewr.me and studying mathematics."
baseurl: /
google_analytics: 'UA-57154869-2'
disqus: 'leonardorifeli'
mailchimp-list: 'https://mailchi.mp/fbb22a1deb63/leonardorifeli'

authors:
  leonardorifeli:
    name: Leonardo Rifeli
    display_name: Leonardo Rifeli
    gravatar: 9797bddafe284a0d23b4e92dd1ce0043
    email: leonardorifeli@gmail.com
    web: https://leonardorifeli.tech
    twitter: https://twitter.com/leonardorifeli
    github: https://github.com/leonardorifeli
    description: "Head of Engineering & Partner at reviewr.me and studying mathematics."

plugins: 
  - jekyll-paginate
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

paginate: 6
paginate_path: /page:num/

markdown: kramdown
highlighter: rouge