baseurl: ""
url: "https://leonardorifeli.com"
markdown: kramdown

theme:
  title: Leonardo Rifeli
  image_home: https://leonardorifeli.com/img/website-avatar.png
  keywords: "joinville, back-end, php, developers brazil, developer, desenvolvedor araraquara, desenvolvedor web, conhecimento, engenharia de computação, engenharia, automação, programação, desenvolvimento, robotica, i.a, inteligencia artificial, dicas de desenvolvimento, dicas de engenharia, logatti, leonardo, leonardo rifeli, augusto rifeli, rifeli, Rifeli"
  description: "teste"
  autor: "Leonardo Rifeli"
  reply: "me@leonardorifeli.com"
  facebookTitle: Leonardo Rifeli
  facebookDescription: "teste"

  header_text: >
     <p>Future engineer, developer and a lifelong learner.</p>

     <p>"My job is to not be easy on people. My job is to make them better." (Steve Jobs).</p>

  rss: false
  email: "me@leonardorifeli.com"
  bitbucket: leonardorifeli
  facebook: "leonardorifeli"
  github: "leonardorifeli"
  linkedin: https://br.linkedin.com/in/leonardorifeli
  twitter: "leonardorifeli"

  google_analytics: "UA-57154869-2"
  disqus_shortname: leonardorifeli
  katex: true
