baseurl: ""
url: "https://leonardorifeli.com"
markdown: kramdown

theme:
  title: Leonardo Rifeli
  image_home: https://leonardorifeli.com/img/website-avatar.png
  keywords: "joinville, back-end, php, developers brazil, developer, desenvolvedor araraquara, desenvolvedor web, conhecimento, engenharia de computação, engenharia, automação, programação, desenvolvimento, robotica, i.a, inteligencia artificial, dicas de desenvolvimento, dicas de engenharia, logatti, leonardo, leonardo rifeli, augusto rifeli, rifeli, Rifeli"
  description: "Meu nome é Leonardo Rifeli, tenho 20 anos e resido em Joinville (SC). Atuo há cerca de três anos no mercado Web, desde então venho adquirindo e aprimorando minhas experiências. Atuo como desenvolvedor back-end na agência taginterativa.com.br. Estou cursando bacharelado em Engenharia de Computação. Contribuo para projetos open source e para a comunidade web como um todo."
  autor: "Leonardo Rifeli"
  reply: "leonardorifeli@gmail.com"
  facebookTitle: Leonardo Rifeli
  facebookDescription: "teste"

  header_text: >
     <p>Future engineer, developer and a lifelong learner.</p>

     <p>"My job is to not be easy on people. My job is to make them better." (Steve Jobs).</p>

  rss: false
  email: "leonardorifeli@gmail.com"
  bitbucket: leonardorifeli
  facebook: "leonardorifeli"
  github: "leonardorifeli"
  linkedin: https://br.linkedin.com/in/leonardorifeli
  twitter: "leonardorifeli"

  google_analytics: "UA-57154869-2"
  disqus_shortname: leonardorifeli
  katex: true
