# SITE CONFIGURATION
baseurl: "/"
url: "https://leonardo.rifeli.tech/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Leonardo Rifeli
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <img src="/assets/header.png"/> <br/><br/>
     <p>Future engineer, head of engineering at reviewr.me and a lifelong learner. <br/> "My job is to not be easy on people. My job is to make them better." (Steve Jobs).</p>
  header_text_feature_image:
  footer_text:

  # Icons
  rss: false
  email_address:
  behance:
  bitbucket:
  dribbble:
  facebook: "leonardorifeli"
  flickr:
  gitlab:
  github: "leonardorifeli"
  google_plus:
  instagram:
  linkedin: "https://br.linkedin.com/in/leonardorifeli"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "leonardorifeli"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
