title: Leonardo Rifeli # The title of the blog
author: Leonardo Rifeli # Your name 
email: leonardorifeli@gmail.com # your email shown in the footer
url: https://rifeli.me/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Co-Founder, Head of Engineering & Developer at @Reviewr.
favicon: "./logo-favicon.png" # set the favicon of the site 

google_analytics: "UA-57154869-2"

keywords: "leonardorifeli.tech, nodejs, spark, hadoop, engineering blog, Leonardo Rifeli, developer, php, joinville, back-end, php, developers brazil, developer, desenvolvedor araraquara, desenvolvedor web, conhecimento, engenharia de computação, engenharia, automação, programação, desenvolvimento, robotica, i.a, inteligencia artificial, dicas de desenvolvimento, dicas de engenharia, logatti, leonardo, leonardo rifeli, augusto rifeli, rifeli, Rifeli"
reply: "leonardorifeli@gmail.com"
description_header: "It's my personal website and blog. More than 8 years of experience. Graduating in Mathematics at UNINTER. Head of Engineering at reviewr.me, a startup incubated at MIDITEC, the 5th best startup incubator in the world and now accelerated by Darwin Startups. Reviewr is the first online review management plataform in Brazil."

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "./assets/leonardorifeli.jpeg" # avatar in about page
  about_you: Co-Founder & Head of Engineering at @Reviewr. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: leonardorifeli
    github:  leonardorifeli
    rss: RSS
    # dribbble: 
    facebook: leonardorifeli
    # flickr:   
    # instagram: 
    linkedin: leonardorifeli
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
